import type { ChartTypePlugin } from '@chartts/core'
import {
  lineChartType,
  barChartType,
  stackedBarChartType,
  horizontalBarChartType,
  pieChartType,
  donutChartType,
  scatterChartType,
  sparklineChartType,
  areaChartType,
  radarChartType,
  bubbleChartType,
  gaugeChartType,
  waterfallChartType,
  funnelChartType,
  heatmapChartType,
  boxplotChartType,
  histogramChartType,
  treemapChartType,
  polarChartType,
  radialBarChartType,
  lollipopChartType,
  bulletChartType,
  dumbbellChartType,
  calendarChartType,
  comboChartType,
  stepChartType,
} from '@chartts/core'

/** Map URL type name → chart type plugin */
export const CHART_TYPES: Record<string, ChartTypePlugin> = {
  line: lineChartType,
  bar: barChartType,
  'stacked-bar': stackedBarChartType,
  'horizontal-bar': horizontalBarChartType,
  pie: pieChartType,
  donut: donutChartType,
  scatter: scatterChartType,
  sparkline: sparklineChartType,
  area: areaChartType,
  radar: radarChartType,
  bubble: bubbleChartType,
  gauge: gaugeChartType,
  waterfall: waterfallChartType,
  funnel: funnelChartType,
  heatmap: heatmapChartType,
  boxplot: boxplotChartType,
  histogram: histogramChartType,
  treemap: treemapChartType,
  polar: polarChartType,
  'radial-bar': radialBarChartType,
  lollipop: lollipopChartType,
  bullet: bulletChartType,
  dumbbell: dumbbellChartType,
  calendar: calendarChartType,
  combo: comboChartType,
  step: stepChartType,
}

export const VALID_TYPES = Object.keys(CHART_TYPES)
